pipeline {
  agent {
    docker { image 'python:3.12-slim' }
  }
  stages {
    stage('Test') {
      steps {
        sh '''
           cd my-first-pipeline
           python3 --version
           python3 test.py
        '''
      }
    }
  }
}
